---
title: "Ryan Pepiot Pitching Report"
author: "Luke Gruendl"
date: "2023-12-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
options(warn=-1)
```


```{r}
# Install Packages

# devtools::install_github("BillPetti/baseballr")
# install.packages("pander")
```


```{r}
# Load Packages

library(baseballr)
library(tidyverse)
library(pander)
```

Data from Ryan Pepiot's 8/30/23 start against the Diamondbacks.

## Pitch Movement Plot

```{r}
pepiot = read_csv("ryan_pepiot_aug_30.csv", show_col_types=FALSE, )
break_data = data.frame(pitch_name = pepiot$pitch_name, 
                       h_break = pepiot$pfx_x*-12, 
                       v_break = pepiot$pfx_z*12)

break_graph = ggplot(break_data, aes(x=h_break, y=v_break, color=pitch_name))
break_graph = break_graph + geom_point() + labs(title='Ryan Pepiot Horizontal Vs. Vertical Break', x='Horizontal Break', y='Induced Vertical break', color='Pitch Type') + xlim(-30, 30) + ylim(-30, 30) + geom_hline(yintercept=0) + geom_vline(xintercept=0)
break_graph
```

## Pitch Movement and Release Data

```{r}
movement_release_data = data.frame(Pitcher = rep('Ryan Pepiot', times = 84),
                       TaggedPitchType = pepiot$pitch_name, 
                       HBreak = pepiot$pfx_x*-12, 
                       VBreak = pepiot$pfx_z*12,
                       Extension = pepiot$release_extension,
                       RelHeight = pepiot$release_pos_z
                       )

avg_mov_rel_data = movement_release_data %>%
    group_by(TaggedPitchType) %>%
    summarize(
        HBreak = mean(HBreak, na.rm = TRUE),
        VBreak = mean(VBreak, na.rm = TRUE),
        Extension = mean(Extension, na.rm = TRUE),
        RelHeight = mean(RelHeight, na.rm = TRUE)
    )

avg_mov_rel_data$Pitcher = 'Ryan Pepiot'
avg_mov_rel_data = avg_mov_rel_data %>% select(Pitcher, everything())

pander(avg_mov_rel_data, caption = "Movement and Release Data by Pitch")
```

## Release Point Plot

```{r}
release_data = data.frame(pitch_name = pepiot$pitch_name, 
                       rel_side = -pepiot$release_pos_x, 
                       rel_height = pepiot$release_pos_z)

release_graph = ggplot(release_data, aes(x=rel_side, y=rel_height, color=pitch_name))
release_graph = release_graph + geom_point() + labs(title='Ryan Pepiot Pitch Release Plot', x='Pitch Release Side (FT)', y='Pitch Release Height (FT)', color='Pitch Type') + xlim(-4.5, 4.5) + ylim(2, 7)
release_graph
```

## Swing Tendency Plot

```{r}
swing_data = data.frame(pitch_name = pepiot$pitch_name, 
                       offset = pepiot$plate_x, 
                       height = pepiot$plate_z,
                       result = pepiot$description,
                       Pitcher = rep('Ryan Pepiot', times=84))

#unique(swing_data$result)

swing_data = swing_data %>%
  mutate(swing_take = case_when(
    swing_data$result %in% c('swinging_strike', 'foul', 'hit_into_play', 'foul_tip', 'foul_bunt') ~ 'Swing',
    swing_data$result %in% c('ball', 'called_strike', 'blocked_ball', 'hit_by_pitch') ~ "Take")
    )

swing_graph = ggplot(swing_data, aes(x=offset, y=height, color=pitch_name, shape=swing_take)) + scale_shape_manual(values = c(16, 4))
swing_graph = swing_graph + geom_point(size=3) + labs(title='Ryan Pepiot Swinging Tendency Chart', x='Pitch Offset (FT)', y='Pitch Height (FT)', color='Pitch Type', shape='Swing or Take') + xlim(-2.5, 2.5) + ylim(0, 5)
swing_graph = swing_graph + annotate("rect", xmin=-0.83, xmax=0.83, ymin=1.5, ymax=3.5, fill=NA, color="black") + coord_fixed(ratio = 1/1)
swing_graph
```

## Discipline Data

```{r}
cum_swing_data = swing_data %>%
    group_by(pitch_name) %>%
    summarize(
        Swings = sum(swing_take=='Swing'),
        Takes = sum(swing_take=='Take')
    )

cum_swing_data$Pitcher = 'Ryan Pepiot'
cum_swing_data = cum_swing_data %>% select(Pitcher, everything())

pander(cum_swing_data, caption = "Discipline Data")
```




```{r}
## EXTRA


#Search for Ryan Pepiot's player information
#player_info <- playerid_lookup("Pepiot", "Ryan")
#print(player_info)
```


```{r}
#start_date <- "2023-04-01"
#end_date <- "2023-09-30"
#player_id <- 686752  # Ryan Pepiot MLBam ID

#statcast_data <- scrape_statcast_savant(start_date = start_date, 
#                                        end_date = end_date, 
#                                        playerid = player_id)
```

